server:
  port: 8082
spring:
  application:
    name: CATALOG-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: eshop
    password: eshop
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

security:
  jwt:
    secret: ${JWT_SECRET:dev-secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
